### PR TITLE
Upgrade to dotnet 2.1

### PR DESCRIPTION
**Pull request by bokobza**
* Swashbuckle.AspNetCore 1.0.0 -> 2.5.0 No breaking changes
* Microsoft.NET.Test.Sdk 15.5.0 -> 15.7.2 No breaking changes
* FluentAssertions 5.2.0 -> 5.4.1 No breaking changes
* Moq 4.8.2 -> 4.8.3 
  Breaking Change: Add ISetupSequentialResult<TResult>.Returns method overload that support delegate for deferred results (@snrnats, #594)
  This change requires the API consumer to specify the type in ISetupSequentialResult<TResult>.Returns when returning null. Otherwise, it is ambiguous whether the type returned is a Type or a Func<Type>.
  https://github.com/moq/moq4/blob/master/CHANGELOG.md

* System.Reactive 3.1.1 -> 4.0.0
* Newtonsoft.Json 10.0.3 -> 11.0.2
* dotnet core 2.0 -> 2.1

✅ Unit tests
✅ Integration tests
✅ 4 blockchains synced

All tests passing apart from 5 consensus-related ones related to another piece of work.
 
image

### CODE REVIEW

**Comment by noescape00** [comment]
Error while building a solution: 

```Version conflict detected for Microsoft.AspNetCore.Antiforgery. Reference the package directly from the project to resolve this issue. 
 Stratis.Bitcoin.Api -> Stratis.Bitcoin -> Microsoft.AspNetCore.Mvc.ViewFeatures 2.1.1 -> Microsoft.AspNetCore.Antiforgery (>= 2.1.1) 
 Stratis.Bitcoin.Api -> Microsoft.AspNetCore.App 2.1.0 -> Microsoft.AspNetCore.Antiforgery (= 2.1.0).	Stratis.Bitcoin.Features.Api	C:\Users\user\Desktop\TeamRepos\Bokobza\src\Stratis.Bitcoin.Features.Api\Stratis.Bitcoin.Features.Api.csproj	1```

Also there are some packages that can be updated: 

![untitled](https://user-images.githubusercontent.com/10259355/42215532-6cfad736-7ec7-11e8-9d4e-dcb5b312c467.png)

They were not updated on purpose or just missed?

**Comment by bokobza** [comment]
Not updated on purpose, I stopped after the update to 2.1.
The integration tests took so long to work that I preferred pushing this now rather than doing this whole dance again.
Did you download the dotnet core SDK 2.1?

**Comment by bokobza** [comment]
Let me get the latest master and see why this is happening.

**Comment by noescape00** [comment]
>Did you download the dotnet core SDK 2.1?

AH, I though I had it. Installed and now it's building.

**Comment by bokobza** [comment]
Thanks, just waiting for the builds to build.

**Comment by bokobza** [comment]
This fails on Appveyor because of these issue:
https://github.com/aspnet/Universe/issues/1180 and https://github.com/aspnet/Home/issues/3180.

Normally, the version on <PackageReference Include="Microsoft.AspNetCore.App" Version="2.1.1" /> should be removed but the only way to get it to build is to have it explicitly set.

**Comment by bokobza** [comment]
Block by another failure:
```
Consensus\ChainedHeaderTreeTest.cs(1365,53): error CS0029: Cannot implicitly convert type 'System.Collections.Generic.List<Stratis.Bitcoin.Primitives.ChainedHeaderBlock>' to 'System.Collections.Generic.List<NBitcoin.ChainedHeader>' 
```

**Comment by bokobza** [comment]
Waiting for https://github.com/stratisproject/StratisBitcoinFullNode/pull/1598 to go in first.

**Comment by noescape00** [comment]
>Waiting for #1598 to go in first.

It's already on master (changes from there), just merge the latest master in

**Comment by monsieurleberre** [comment]
let's go !

**Comment by dangershony** [comment]
The 5 consensus changes are fine (there is a fix)
Please not after this upgrade everyone running a node will have to install dotnet core 2.1
So we should **notify the community** and provide a link tot he upgrade.

If I am not mistaken no need to uninstall version 2.0
